//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreMobileWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int bookId { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string short_description { get; set; }
        public string releaseDate { get; set; }
        public byte[] image { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> rating { get; set; }
        public string longDesc { get; set; }
    }
}
